### ISSUE TITLE
Creating a database with BLAST

### ISSUE THREAD

**Issue by mash23** [GMOD/jblast-jbconnect-hook#174]
Hi, 
I want to create a peptide database for a certain proteome. So I downloaded a fasta file with the proteome from UNIPROT. Are there any tools in BLAST that can cut proteins in the proteome to peptides or something and create a database out of this cutting ?

**Comment by enuggetry** [comment]
I don't think you can cut proteins to peptides with NCBI blast, but you should be able to create a blast database from peptide sequences.  However, I'm generally not familiar this process.
https://www.ncbi.nlm.nih.gov/books/NBK279688/
