### ISSUE TITLE
"Family" consistently mis-spelled "Familly" in demo instance

### ISSUE THREAD

**Issue by ihh** [GMOD/jblast-jbconnect-hook#228]

**Comment by enuggetry** [comment]
can you show me where you saw this?

**Comment by ihh** [comment]
In the track list
<img width="505" alt="Screen Shot 2019-05-08 at 5 32 11 PM" src="https://user-images.githubusercontent.com/54113/57416958-50cbd400-71b7-11e9-912f-3b855c375350.png">
