### ISSUE TITLE
If the highlight button is selected, but no region is highlighted yet, then "BLAST highlighted region" fails silently with no error

### ISSUE THREAD

**Issue by ihh** [GMOD/jblast-jbconnect-hook#229]

**Comment by enuggetry** [comment]
Resolution, just don't automatically highlight the region have a better popup description from the "BLAST highlighted region" menu option, perhaps.

**Comment by ihh** [comment]
Will this resolve the issue as described? i.e.

> if the highlight button is selected, but no region is highlighted yet, then "BLAST highlighted region" fails silently with no error

**Comment by enuggetry** [comment]
Perhaps I can implement this:
If the user has selected a highlighted region on his own, then the menu option will launch the blast dialog, allowing him to choose the workflow.
if no actual region is selected, the menu option will display the help popup.

**Comment by ihh** [comment]
That sounds good, although be careful because the highlight button is a toggle, so if the help message says "First click the highlight button...." but the highlight button is already clicked, clicking it again will de-select highlighting mode.

Probably the correct thing is to have two slightly different help messages: one for if the highlight button is clicked, one if it's not clicked. The second message should give some hint of encouragement/accomplishment, relative to the first, so that if the user sees both messages, they understand they've made progress. E.g. (just to give the general idea, feel free to polish the text a bit)

First message: "You have selected the 'BLAST highlighted region' option, but no region is highlighted. First you need to click the highlight button, then drag a region to select it, then come back here"

Second message: "You have selected the 'BLAST highlighted region' option, and although you have clicked the highlight button, no region has been highlighted yet. You now need to drag a region to select it, then come back here"
