### ISSUE TITLE
"Sample sequence" in "BLAST DNA sequence" dialog should be identified

### ISSUE THREAD

**Issue by ihh** [GMOD/jblast-jbconnect-hook#231]
Please change button text from "Sample sequence" to the more standard "Example: TraesCS1A02G160100" (or a shorter name if there is one)

**Comment by enuggetry** [comment]
Applied to button name with tooltip.
```
               "button": "Sample Seq TraesCS1A02G160100",
                "description": "Insert sample sequence, a fragment of TraesCS1A02G160100",

```
![image](https://user-images.githubusercontent.com/10053377/57443940-f9a02080-7203-11e9-9b5f-bc6f47b446cf.png)

**Comment by ihh** [comment]
Can you please change the text `Sample Seq` to `Example:` (with a colon)

Thanks

**Comment by enuggetry** [comment]
"button": "Example: TraesCS1A02G160100",
                "description": "Inserts a fragment of example sequence, TraesCS1A02G160100",
