### ISSUE TITLE
Info popup should only appear the first time

### ISSUE THREAD

**Issue by ihh** [GMOD/jblast-jbconnect-hook#236]
The info popup, while helpful in that it contains a link to documentation, is annoying if you're already logged in or know what you're doing. Ideally it should only open by default once, the first time you visit the site.

Also, it should disappear if you click outside it (rather than just via the close button or the timeout).

**Comment by ihh** [comment]
Moved to https://github.com/GrainGenes/LogoButton/issues/12

**Comment by enuggetry** [comment]
This is a LogoButton feature and has been moved https://github.com/GrainGenes/LogoButton/issues/12
