### ISSUE TITLE
possibly jblastTrackTemplate.json not being copied for 2nd dataset to jblastdata dir

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jblast-jbconnect-hook#266]
this should be happening in: jbutil --setupdata, i think.
jblastTrackTemplate.json is the baseline JBrowse track template for jblast result tracks.
I suspect it might not be copying properly to a 2nd dataset that is configured.

**Comment by ihh** [comment]
@enuggetry Can you please advance this further: refine the issue description so it is clearer why this is a problem and/or investigate so that you can remove the "possibly" and "i think" caveats.

**Comment by ihh** [comment]
Also add "bug" label if appropriate.

**Comment by enuggetry** [comment]
It is believed to be working:
https://github.com/GMOD/jblast-jbconnect-hook/blob/master/bin/jbutil-ext.js#L249
