### ISSUE TITLE
apply user access controls

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jblast-jbconnect-hook#273]
Add access controls so that a user can only see the results of their own analyses, and only when logged in. The way we discussed doing this was by having the job results track list included by the main trackList.json, using a path that actually resolves (via a Sails route) to a REST call which (through being part of Sails) knows whether the user is logged in & who they are.

**Comment by ihh** [comment]
@enuggetry is this still incomplete?

**Comment by enuggetry** [comment]
this was address in https://github.com/GMOD/jbconnect/issues/162
